FROM golang:1.25-alpine

WORKDIR /app

# install air untuk hot reload
RUN go install github.com/air-verse/air@latest

# cache dependency
COPY go.mod go.sum ./
RUN go mod download

# copy source
COPY . .

EXPOSE 8081

CMD ["air"]
