FROM node:20-alpine

WORKDIR /app

RUN corepack enable

# copy dependency files dulu (cache layer)
COPY package.json pnpm-lock.yaml ./

RUN pnpm install

# ⭐ COPY SOURCE supaya container punya project valid
COPY . .

CMD ["pnpm", "run", "start:dev"]